# Generated by Django 5.2.11 on 2026-04-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_gallerymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='bus_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='hostel_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='hostel_fees',
            field=models.CharField(blank=True, help_text='e.g. ₹50,000/year', max_length=100, null=True),
        ),
    ]
