# Generated by Django 5.2.11 on 2026-04-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_college_bus_available_college_hostel_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('caste', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=50)),
                ('score', models.CharField(help_text='e.g. 95.5%', max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='colleges.college')),
            ],
            options={
                'unique_together': {('college', 'course', 'year', 'caste')},
            },
        ),
    ]
