# Generated by Django 5.2.11 on 2026-04-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_alter_college_description_alter_college_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='degree_type',
            field=models.CharField(default='B.E/B.TECH', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='established_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
