# Generated by Django 5.2.11 on 2026-04-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_course_average_package_course_degree_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='mission',
            field=models.TextField(blank=True, help_text='College mission statement', null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='vision',
            field=models.TextField(blank=True, help_text='College vision statement', null=True),
        ),
    ]
