version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: college_lens_backend
    environment:
      - AWS_DEFAULT_REGION=ap-south-1
      - S3_BUCKET_NAME=college-lens-ml-model
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DEBUG=False
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: college_lens_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always