# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY Frontend/package*.json ./

RUN npm install

COPY Frontend/ .

RUN npm run build

# Stage 2: Nginx
FROM nginx:alpine

# 'build' hai 'dist' nahi — teri config ke hisaab se
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]