server {
    listen 80;

    # React frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Django API proxy
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # ML model ke liye timeout badha ke rakha hai
        proxy_read_timeout 120s;
        proxy_connect_timeout 120s;
        client_max_body_size 20M;
    }

    # Django media files (uploaded PDFs, images)
    location /media/ {
        proxy_pass http://backend:8000/media/;
        proxy_set_header Host $host;
    }

    # Django admin
    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}