# Generated by Django 5.2.11 on 2026-03-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hsc_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diploma_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('jee_mains_rank', models.IntegerField(blank=True, null=True)),
                ('jee_mains_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
