# Generated by Django 5.2.11 on 2026-03-30 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_gallerymedia'),
        ('users', '0002_counsellingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='marksheet_first_year',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
