# Generated by Django 5.2.11 on 2026-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_branch_studentprofile_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='degree_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='fees_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
